server:
  port: 8001
  tomcat:
    max-http-post-size:

security:
  oauth2:
    client:
      clientId: resource_user
      clientSecret: 123
      userAuthorizationUri: http://localhost:9000/oauth/authorize
      grant-type: authorization_code
      scope: all
      access-token-uri: http://localhost:9000/oauth/token
    resource:
      userInfoUri: http://localhost:9000/user
    authorization:
      check-token-access: http://localhost:9000/oauth/check_token




spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    # hikari数据源配置，
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

# springboot-admin
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#  zipkin:
#    base-url: http://127.0.0.1:9411/ #zipkin server的请求地址
#    discoveryClientEnabled: false #让nacos把它当成一个URL，而不要当做服务名
#  sleuth:
#    sampler:
#      probability: 1.0 #采样的百分比
